volunteer-python/volunteer/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    # url(r'', include(('volunteers.urls', 'volunteers'), namespace='volunteers')),
    path('volunteer/', include(('volunteers.urls', 'volunteers'), namespace='volunteers')),
]

volunteer-python/volunteers/urls.py
from django.conf.urls import url

from volunteer import settings
from volunteers import views

urlpatterns = [
    # Home page
    url(r'^$', views.index, name='index'),
    url(r'index.html$', views.index, name='index'),
    # Show all topics.
    url(r'^topics/$', views.topics, name='topics'),

]

volunteer-python/volunteers/models.py
from django.db import models


# Create your models here.
class Topic(models.Model):
    """A topic the user is learning about"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)


def __str__(self):
    """Return a string representation of the model."""
    return self.text


class Entry(models.Model):
    """Something specific learned about a topic"""
    # topic = models.ForeignKey(Topic)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'


def __str__(self):
    """Return a string representation of the model."""
    return self.text[:50] + "..."

volunteer-python/volunteers/views.py
from django.shortcuts import render


# Create your views here.
from volunteers.models import Topic


def index(request):
    """The home page for Learning Log"""
    return render(request, 'index.html')

def topics(request):
    """Show all topics."""
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'topics.html', context)

volunteer-python/volunteers/templates/a.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div id="myCarousel" class="carousel slide">
    <!-- 轮播（Carousel）指标 -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- 轮播（Carousel）项目 -->
    <div class="carousel-inner" >
        <div class="item active">
            <img style="width: 100%" src="{% static "img/poster1.png" %}" alt="First slide">
        </div>
        <div class="item">
            <img style="width: 100%" src="{% static "img/poster3.png" %}" alt="Second slide">
        </div>
        <div class="item">
            <img style="width: 100%" src="{% static "img/poster1.png" %}" alt="Third slide">
        </div>
    </div>
    <!-- 轮播（Carousel）导航 -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

{% endblock content %}

volunteer-python/volunteers/templates/base.html
{% load bootstrap3 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="{% static "css/base.css" %}" rel="stylesheet" type="text/css"/>

    <title>志愿者服务活动中心</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed"
                    data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
            </button>
            <a class="navbar-brand" href="{% url 'blogs:index' %}" style="font-size: 25px;">
                志愿者服务活动中心</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav dropdown-hover">
                <!-- <li><a href="{% url 'volunteers:topics' %}">Topics</a></li>-->

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" >文明XX
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="#">热门</a></li>
                            <li><a href="#">最新</a></li>
                        </ul>
                    </a>
                </li>

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" >XX志愿者APP
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="#">项目介绍</a></li>
                            <li><a href="#">新闻专栏</a></li>
                            <li><a href="#">志愿招募</a></li>
                            <li><a href="#">活动地图</a></li>
                        </ul>
                    </a>
                </li>

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" >XX志愿者网
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="#">项目介绍</a></li>
                            <li><a href="#">新闻专栏</a></li>
                            <li><a href="#">宣传视频</a></li>
                            <li><a href="#">专题活动</a></li>
                        </ul>
                    </a>
                </li>

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" >雷锋热线
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="#">项目介绍</a></li>
                            <li><a href="#">新闻专栏</a></li>
                            <li><a href="#">我要求助</a></li>
                            <li><a href="#">我要帮扶</a></li>
                            <li><a href="#">品牌活动</a></li>
                            <li><a href="#">宣传视频</a></li>
                        </ul>
                    </a>
                </li>


                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" >公益活动
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="#">让轮椅飞</a></li>
                            <li><a href="#">名师一堂课</a></li>
                            <li><a href="#">睡前讲故事</a></li>
                        </ul>
                    </a>
                </li>

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">公益广告
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="#">图说我们的价值观</a></li>
                            <li><a href="#">“讲文明 树新风”公益广告</a></li>
                        </ul>
                    </a>
                </li>
            </ul>

        </div>
    </div>

    <div class="container">
        <div class="page-header">
            {% block header %}{% endblock header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </div> <!-- /container -->
</nav>
</body>
</html>

volunteer-python/volunteers/templates/index.html

{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title></title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static "css/reset.css" %}" type="text/css" media="all">
    <link rel="stylesheet" href="{% static "css/grid.css" %}" type="text/css" media="all">
    <link rel="stylesheet" href="{% static "css/style.css" %}" type="text/css" media="all">
    <link rel="stylesheet" href="{% static "css/jquery-ui-1.8.5.custom.css" %}" type="text/css" media="all">

    <script type="text/javascript" src="{% static "js/jquery-1.4.2.min.js" %} "></script>
    <script type="text/javascript" src="{% static "js/jquery.cycle.all.js" %}"></script>
    <script type="text/javascript" src="{% static "js/jquery-ui-1.8.5.custom.min.js" %}"></script>
    <!--[if lt IE 9]>
    <script type="text/javascript" src="{% static "js/html5.js" %}"></script>
    <![endif]-->

</head>

<body>

<header>
    <nav>
        <div class="container">
            <div class="wrapper">
                <h1><a href="index.html"><strong>志愿者服务活动中心</strong></a></h1>
                <ul>
                    <li><a href="index.html" class="current">文明XX</a></li>
                    <li><a href="index.html">XX志愿者APP</a></li>
                    <li><a href="index.html">XX志愿者网</a></li>
                    <li><a href="index.html">雷锋热线</a></li>
                    <li><a href="index.html">公益活动</a></li>
                    <li><a href="index.html">公益广告</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <section class="adv-content">
        <div class="container">
            <ul class="breadcrumbs">
                <li>首页</li>
            </ul>
            <form action="" id="search-form">
                <fieldset>
                    <input type="text" value=""><input type="submit" value="">
                </fieldset>
            </form>
        </div>
    </section>
</header>

<section id="content">
    <div class="top">
        <div class="container">
            <div class="clearfix">
                <section id="gallery">
                    <div class="pics">
                        <img src="{% static "img/poster1.png" %}" alt="" width="495" height="329">
                        <img src="{% static "img/poster2.png" %}" alt="" width="495" height="329">
                        <img src="{% static "img/poster3.png" %}" alt="" width="495" height="329">

                    </div>
                    <a href="#" id="prev"></a>
                    <a href="#" id="next"></a>
                </section>
                <section id="intro">
                    <div class="inner">
                        <h2>志愿者活动中心</h2>
                        <p style="font-size: 18px">志愿者（Volunteer）联合国定义为“自愿进行社会公共利益服务而不获取任何利益、金钱、名利的活动者”，具体指在不为任何物质报酬的情况下，能够主动承担社会责任而不获取报酬，奉献个人时间和行动的人。
                            根据中国的具体情况来说，志愿者是这样定义的：“在自身条件许可的情况下，参加相关团体，在不谋求任何物质、金钱及相关利益回报的前提下，在非本职职责范围内，合理运用社会现有的资源，服务于社会公益事业，为帮助有一定需要的人士，开展力所能及的、切合实际的，具一定专业性、技能性、长期性服务活动的人。"
                            自愿参与社会公益活动的人。享受乘坐公交车，地铁免费，免费进公园及旅游景点。
                            志愿者也叫义工、义务工作者或志工。他们致力于免费、无偿地为社会进步贡献自己的力量。 志愿工作是指一种具有组织性的助人及基于社会公益责任的参与行为，其发展可追溯至第二次世界大战后，福利主义抬头导致各国政府支出崩塌，发展义务工作以解决社会上不胜负荷的需求。</p>
                        <a href="#" class="extra-button">更多</a>
                    </div>
                </section>
            </div>
        </div>
    </div>
    <div class="middle">
        <div class="container">
            <div class="wrapper">
                <div class="grid3 first">
                    <ul class="categories">
                        <li><a href="#">文明XX</a></li>
                        <li><a href="#">XX志愿者APP</a></li>
                        <li><a href="#">XX志愿者网</a></li>
                        <li><a href="#">雷锋热线</a></li>
                        <li><a href="#">公益活动</a></li>
                        <li><a href="#">公益广告</a></li>
                    </ul>
                </div>
                <div class="grid9">
                    <h2>2018年大学生志愿服务西部计划启动
                    </h2>
                    <p style="font-size: 18px"> 4月23日，共青团中央、教育部、财政部、人力资源社会保障部联合召开电视电话会议，启动2018年大学生志愿服务西部计划。团中央书记处书记尹冬梅、教育部高校学生司副司长孙海波、财政部行政政法司副司长区利民、人力资源社会保障部人力资源市场司副司长高占胜出席会议并讲话。各省（区、市）团委、教育、财政、人社部门负责人及省级西部计划项目办、重点招募高校项目办负责人在分会场参加会议。

                        尹冬梅指出，在各级党委政府的关心支持下，在各级教育、财政、人社部门和共青团组织的共同努力下，在广大西部计划志愿者的倾情奉献下，2017年西部计划各项工作有序实施，圆满完成18300名志愿者的招募派遣工作，各地的服务保障水平进一步加强，各级项目办管理水平进一步提升，西部计划综合效应进一步彰显，受到各服务单位和广大群众的认可欢迎。</p>
                    <p><a href="#" class="more">更多</a></p>
                    <section class="images">
                        <figure><a href="#"><img src="{% static "img/1page-img1.jpg" %}" alt=""></a></figure>
                        <figure><a href="#"><img src="{% static "img/1page-img2.jpg" %}" alt=""></a></figure>
                        <figure><a href="#"><img src="{% static "img/1page-img3.jpg" %}" alt=""></a></figure>
                    </section>
                </div>
            </div>
        </div>
    </div>
    <div class="bottom">
        <div class="container">
            <div class="wrapper">
               <!-- <div class="grid3 first">
                    <h3>Database</h3>
                    <ul class="list1">
                        <li><a href="#">Real Application Clusters</a></li>
                        <li><a href="#">Database Security</a></li>
                        <li><a href="#">Secure Enterprise Search</a></li>
                    </ul>
                </div>
                <div class="grid3">
                    <h3>Quick Links</h3>
                    <ul class="list2">
                        <li><a href="#">Certification</a></li>
                        <li><a href="#">Education</a></li>
                        <li><a href="#">Careers</a></li>
                        <li><a href="#">For Midsize Companies</a></li>
                        <li><a href="#">Investors</a></li>
                        <li><a href="#">Technology Network</a></li>
                        <li><a href="#">FAQs</a></li>
                    </ul>
                </div>
                <div class="grid3">
                    <h3>Top Downloads</h3>
                    <ul class="list2">
                        <li><a href="#">Enterprise Architecture</a></li>
                        <li><a href="#">Enterprise 2.0</a></li>
                        <li><a href="#">Grid</a></li>
                        <li><a href="#">Service-Oriented Architecture</a></li>
                        <li><a href="#">Virtualization</a></li>
                        <li><a href="#">Database XE</a></li>
                        <li><a href="#">Enterprise Management</a></li>
                    </ul>
                </div>-->
                <div class="grid3">
                    <div id="datepicker"></div>
                </div>
            </div>
        </div>
    </div>
</section>
<footer>
    <div class="container">
        <div class="wrapper">
            <div class="copy">Industrial Services (c) 2010 | <a href="index-4.html">Privacy
                policy</a></div>
            <address class="phone">
                We're glad to help you. Please email or call us. <strong>1-123-456-7890</strong>
            </address>
        </div>
    </div>
</footer>
<script type="text/javascript">
    $(document).ready(function () {
        $('.pics').cycle({
            fx: 'toss',
            next: '#next',
            prev: '#prev'
        });

        // Datepicker
        $('#datepicker').datepicker({
            inline: true
        });

    });
</script>
</body>
</html>

volunteer-python/volunteers/templates/topics.html
{% extends "base.html" %}
{% block header %}
<h1>Topics</h1>
{% endblock header %}

{% block content %}
<ul>
    {% for topic in topics %}
    <li>{{ topic }}</li>
    {% empty %}
    <li>No topics have been added yet.</li>
    {% endfor %}
</ul>
{% endblock content %}